# Initial Draft EDA and Machine Learning

This isn't the notebook that will be exported and sent in as a submission. This is ONLY to be used as a draft to inform the submission

In [1]:
# Initial imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Import data

In [2]:
df_1950s = pd.read_csv("data/1950.csv")
df_1960s = pd.read_csv("data/1960.csv")
df_1970s = pd.read_csv("data/1970.csv")
df_1980s = pd.read_csv("data/1980.csv")
df_1990s = pd.read_csv("data/1990.csv")
df_2000s = pd.read_csv("data/2000.csv")
df_2010s = pd.read_csv("data/2010.csv")

In [3]:
df_1950s

,Number,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,Put Your Head On My Shoulder,Paul Anka,adult standards,2000,116,34,55,-9,10,47,155,75,3,72
1,2,Whatever Will Be Will Be (Que Sera Sera) (with...,Doris Day,adult standards,1948,177,34,42,-11,72,78,123,86,4,62
2,3,Everybody Loves Somebody,Dean Martin,adult standards,2013,81,49,26,-9,34,40,162,81,4,61
3,4,Take Good Care Of My Baby - 1990 Remastered,Bobby Vee,adult standards,2011,82,43,49,-12,12,66,151,70,6,60
4,5,A Teenager In Love,Dion & The Belmonts,adult standards,1959,79,38,56,-9,13,62,158,67,3,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,69,Collette,Billy Fury,adult standards,1982,155,44,55,-10,10,73,112,82,4,27
69,70,Happy Days And Lonely Nights,Suzi Miller And Johnson Brothers,NaN,2012,142,38,65,-8,13,69,146,43,3,27
70,71,Stairway Of Love,Terry Dene,NaN,2015,93,62,62,-7,25,86,120,55,4,27
71,72,I've Waited So Long,Anthony Newley,NaN,2012,137,36,27,-15,25,28,165,64,4,26
72,73,Held for Questioning,Rusty Draper,deep adult standards,1953,109,65,70,-2,14,85,146,79,3,26

In [4]:
df_1960s

,Number,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,Here Comes The Sun - Remastered 2009,The Beatles,british invasion,1969,129,54,56,-10,18,39,186,3,3,82
1,2,Come Together - Remastered 2009,The Beatles,british invasion,1969,165,38,53,-12,9,19,260,3,4,79
2,3,Sweet Caroline,Neil Diamond,adult standards,1969,63,13,53,-16,24,58,204,61,3,78
3,4,Yesterday - Remastered 2009,The Beatles,british invasion,1965,97,18,33,-12,9,32,126,88,3,78
4,5,Can't Help Falling in Love,Elvis Presley,adult standards,1961,100,29,40,-14,11,34,182,94,3,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,93,A World Without Love,Peter And Gordon,brill building pop,2017,130,66,51,-10,11,75,161,23,6,37
93,94,Don't Break The Heart That Loves You,Connie Francis,adult standards,1996,73,41,39,-6,20,20,182,82,3,37
94,95,Live Wire,The Meters,afrobeat,1969,114,77,68,-12,17,96,160,27,4,36
95,96,Laugh Laugh,The Beau Brummels,brill building pop,2006,129,68,49,-9,10,75,177,30,5,30
96,97,Peppermint Twist Pt.1,Joey Dee,australian talent show,2019,199,73,42,-11,73,72,122,37,14,30

In [5]:
df_1980s

,Number,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,Livin' On A Prayer,Bon Jovi,glam metal,1986,123,89,53,-4,29,80,249,8,3,83
1,2,Africa,TOTO,album rock,1982,93,37,67,-18,5,73,296,26,3,83
2,3,Another One Bites The Dust - Remastered 2011,Queen,glam rock,1980,110,53,93,-6,16,75,215,11,16,82
3,4,Break My Stride,Matthew Wilder,new wave pop,1983,110,59,92,-11,9,83,184,20,6,81
4,5,I Wanna Dance with Somebody (Who Loves Me),Whitney Houston,dance pop,1987,119,82,71,-9,9,87,291,21,5,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,101,Cold as Ice - 2008 Remaster,Foreigner,album rock,2008,131,71,55,-5,14,51,200,6,3,57
101,102,Zulu Nation Throw Down,Afrika Bambaataa,bronx hip hop,2015,108,95,85,-4,10,91,433,76,19,50
102,103,It's Only Love - 2008 Remaster,Simply Red,british soul,2008,92,88,67,-5,4,75,299,51,4,50
103,104,Lucky Star,Madonna,dance pop,1983,117,81,80,-5,22,93,338,20,4,46
104,105,Romeo - 2014 Remaster,Donna Summer,dance pop,1996,141,85,85,-8,11,96,199,3,4,43

In [6]:
df_1990s

,Number,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,No Scrubs,TLC,atl hip hop,1999,93,68,74,-4,7,59,214,3,10,79
1,2,I Want It That Way,Backstreet Boys,boy band,2001,99,70,69,-6,16,48,214,22,3,76
2,3,It Wasn't Me,Shaggy,dance pop,2000,95,61,85,-5,31,65,228,6,7,76
3,4,"Because You Loved Me (Theme from ""Up Close and...",CÃ©line Dion,canadian pop,1996,120,47,61,-10,10,18,274,31,3,74
4,5,Big Poppa - 2005 Remaster,The Notorious B.I.G.,east coast hip hop,1994,84,58,78,-7,14,76,253,43,27,74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,84,Insomnia - Radio Edit,Faithless,big beat,2010,127,92,71,-9,37,53,216,6,4,50
84,85,If You Ever,East 17,boy band,1996,140,68,58,-9,31,57,255,18,3,48
85,86,Pump Up The Jam,Technotronic,eurodance,2019,125,84,89,-9,5,72,320,1,7,46
86,87,Doin' It,LL Cool J,east coast hip hop,1996,95,53,81,-12,12,62,294,34,19,46
87,88,Please Forgive Me,Bryan Adams,album rock,2005,67,46,53,-7,10,15,356,50,3,43

In [7]:
df_2000s

,Number,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,In the End,Linkin Park,alternative metal,2000,105,86,56,-6,21,40,217,1,6,83
1,2,The Scientist,Coldplay,permanent wave,2002,146,44,56,-7,11,21,310,73,2,83
2,3,Numb,Linkin Park,alternative metal,2003,110,86,50,-4,64,24,186,0,4,81
3,4,Fix You,Coldplay,permanent wave,2005,138,42,21,-9,11,12,296,16,3,81
4,5,Umbrella,Rihanna,barbadian pop,2008,174,83,58,-5,4,57,276,1,13,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,I Know What You Want (feat. Flipmode Squad),Busta Rhymes,east coast hip hop,2002,86,75,56,-4,64,49,324,1,32,56
96,97,Knock You Down,Keri Hilson,dance pop,2009,155,88,59,-5,17,65,326,1,16,56
97,98,Dragostea Din Tei - Italian Version,O-Zone,bubblegum dance,2010,130,89,67,-6,10,80,215,4,3,44
98,99,What A Girl Wants - Eddie Arroyo Dance Radio Edit,Christina Aguilera,dance pop,1999,130,92,75,-7,7,66,244,1,3,40
99,100,Impossible - Main,Shontelle,barbadian pop,2019,90,57,59,-5,11,51,226,44,4,32

In [8]:
df_2010s

,Number,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,bad guy,Billie Eilish,electropop,2019,135,43,70,-11,10,56,194,33,38,94
1,2,7 rings,Ariana Grande,dance pop,2019,140,32,78,-11,9,33,179,59,33,90
2,3,Old Town Road - Remix,Lil Nas X,country rap,2019,136,62,88,-6,11,64,157,5,10,89
3,4,SeÃ±orita,Shawn Mendes,canadian pop,2019,117,55,76,-6,8,75,191,4,3,88
4,5,rockstar (feat. 21 Savage),Post Malone,dfw rap,2018,160,52,59,-6,13,13,218,12,7,88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Stereo Hearts (feat. Adam Levine),Gym Class Heroes,dance pop,2011,90,80,65,-3,27,80,211,3,10,56
96,97,Dynamite,Taio Cruz,dance pop,2011,120,79,76,-4,3,87,203,0,8,56
97,98,Break Your Heart,Taio Cruz,dance pop,2011,122,89,67,-5,24,68,185,0,3,54
98,99,Summer Air,ItaloBrothers,dance pop,2017,102,75,76,-4,8,49,184,6,7,43
99,100,All I Wanna Do,Martin Jensen,big room,2016,112,79,73,-4,7,56,194,16,7,32

# Clean data

In [9]:
# Add decade column for each df
dfs = [df_1950s, df_1960s, df_1970s, df_1980s, df_1990s, df_2000s, df_2010s]
decades = [1950, 1960, 1970, 1980, 1990, 2000, 2010]

for df in dfs:
    df["decade"] = decades.pop(0)

In [10]:
# Combine the dataset
combined_df = pd.concat(dfs, ignore_index=True)
print(combined_df.shape)

(667, 16)

In [11]:
combined_df

,Number,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop,decade
0,1,Put Your Head On My Shoulder,Paul Anka,adult standards,2000,116,34,55,-9,10,47,155,75,3,72,1950
1,2,Whatever Will Be Will Be (Que Sera Sera) (with...,Doris Day,adult standards,1948,177,34,42,-11,72,78,123,86,4,62,1950
2,3,Everybody Loves Somebody,Dean Martin,adult standards,2013,81,49,26,-9,34,40,162,81,4,61,1950
3,4,Take Good Care Of My Baby - 1990 Remastered,Bobby Vee,adult standards,2011,82,43,49,-12,12,66,151,70,6,60,1950
4,5,A Teenager In Love,Dion & The Belmonts,adult standards,1959,79,38,56,-9,13,62,158,67,3,60,1950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,96,Stereo Hearts (feat. Adam Levine),Gym Class Heroes,dance pop,2011,90,80,65,-3,27,80,211,3,10,56,2010
663,97,Dynamite,Taio Cruz,dance pop,2011,120,79,76,-4,3,87,203,0,8,56,2010
664,98,Break Your Heart,Taio Cruz,dance pop,2011,122,89,67,-5,24,68,185,0,3,54,2010
665,99,Summer Air,ItaloBrothers,dance pop,2017,102,75,76,-4,8,49,184,6,7,43,2010
666,100,All I Wanna Do,Martin Jensen,big room,2016,112,79,73,-4,7,56,194,16,7,32,2010

In [12]:
# Don't need the number column, relic from combining
combined_df = combined_df.drop(columns=["Number"])

In [13]:
# Check for any rows where title and artist are the same
combined_df[combined_df.duplicated(["title", "artist"])]
# There's 7

,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop,decade
81,Put Your Head On My Shoulder,Paul Anka,adult standards,2000,116,34,55,-9,10,47,155,75,3,72,1960
97,Take Good Care Of My Baby - 1990 Remastered,Bobby Vee,adult standards,2011,82,43,49,-12,12,66,151,70,6,60,1960
131,Everybody Loves Somebody,Dean Martin,adult standards,2014,119,41,50,-12,35,46,164,86,4,49,1960
329,Guilty (feat. Barry Gibb),Barbra Streisand,adult standards,1980,151,43,63,-16,11,95,264,23,4,67,1980
615,Hall of Fame,The Script,celtic rock,2012,85,87,42,-4,12,63,203,7,6,78,2010
663,Dynamite,Taio Cruz,dance pop,2011,120,79,76,-4,3,87,203,0,8,56,2010
664,Break Your Heart,Taio Cruz,dance pop,2011,122,89,67,-5,24,68,185,0,3,54,2010

In [14]:
# Sort by year and keep earliest
combined_df = combined_df.sort_values("year", ascending=True)
combined_df = combined_df.drop_duplicates(subset=["title", "artist"], keep="first")
combined_df = combined_df.reset_index(drop=True)

In [15]:
combined_df

,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop,decade
0,If I Give My Heart to You (with The Mellomen) ...,Doris Day,adult standards,1945,77,6,50,-16,10,33,169,97,5,52,1950
1,Whatever Will Be Will Be (Que Sera Sera) (with...,Doris Day,adult standards,1948,177,34,42,-11,72,78,123,86,4,62,1950
2,Held for Questioning,Rusty Draper,deep adult standards,1953,109,65,70,-2,14,85,146,79,3,26,1950
3,Only Because,The Platters,adult standards,1957,73,28,55,-10,9,47,174,85,3,44,1950
4,Chicago - Remastered,Frank Sinatra,adult standards,1958,148,46,51,-10,40,79,134,61,7,47,1950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,SeÃ±orita,Shawn Mendes,canadian pop,2019,117,55,76,-6,8,75,191,4,3,88,2010
656,bad guy,Billie Eilish,electropop,2019,135,43,70,-11,10,56,194,33,38,94,2010
657,Marianne,The Hilltoppers,deep adult standards,2019,106,55,71,-8,19,82,137,73,4,33,1950
658,Someone Elses Roses,Joan Regan,NaN,2019,100,14,29,-10,15,32,143,89,3,34,1950
659,When You Love Someone,James TW,neo mellow,2019,126,45,68,-6,5,35,217,26,3,76,2010

In [16]:
# Check again
combined_df[combined_df.duplicated(["title", "artist"])]

Empty DataFrame
Columns: [title, artist, top genre, year, bpm, nrgy, dnce, dB, live, val, dur, acous, spch, pop, decade]
Index: []

## Fix NA/Null

In [17]:
combined_df.isnull().sum()

title         0
artist        0
top genre    16
year          0
bpm           0
nrgy          0
dnce          0
dB            0
live          0
val           0
dur           0
acous         0
spch          0
pop           0
decade        0
dtype: int64

In [18]:
# Keep rows but replace nulls with "unknown"
combined_df["top genre"] = combined_df["top genre"].fillna("unknown")
combined_df

,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop,decade
0,If I Give My Heart to You (with The Mellomen) ...,Doris Day,adult standards,1945,77,6,50,-16,10,33,169,97,5,52,1950
1,Whatever Will Be Will Be (Que Sera Sera) (with...,Doris Day,adult standards,1948,177,34,42,-11,72,78,123,86,4,62,1950
2,Held for Questioning,Rusty Draper,deep adult standards,1953,109,65,70,-2,14,85,146,79,3,26,1950
3,Only Because,The Platters,adult standards,1957,73,28,55,-10,9,47,174,85,3,44,1950
4,Chicago - Remastered,Frank Sinatra,adult standards,1958,148,46,51,-10,40,79,134,61,7,47,1950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,SeÃ±orita,Shawn Mendes,canadian pop,2019,117,55,76,-6,8,75,191,4,3,88,2010
656,bad guy,Billie Eilish,electropop,2019,135,43,70,-11,10,56,194,33,38,94,2010
657,Marianne,The Hilltoppers,deep adult standards,2019,106,55,71,-8,19,82,137,73,4,33,1950
658,Someone Elses Roses,Joan Regan,unknown,2019,100,14,29,-10,15,32,143,89,3,34,1950
659,When You Love Someone,James TW,neo mellow,2019,126,45,68,-6,5,35,217,26,3,76,2010

## Fix incoherent years

In [19]:
# We can keep everything in for now, but add flag for year that deosn't fall within it's decade
combined_df["incoherent_year"] = combined_df.apply(
    lambda row: 1 if row["year"] < row["decade"] or row["year"] > row["decade"] + 9 else 0,
    axis=1)

combined_df

,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop,decade,incoherent_year
0,If I Give My Heart to You (with The Mellomen) ...,Doris Day,adult standards,1945,77,6,50,-16,10,33,169,97,5,52,1950,1
1,Whatever Will Be Will Be (Que Sera Sera) (with...,Doris Day,adult standards,1948,177,34,42,-11,72,78,123,86,4,62,1950,1
2,Held for Questioning,Rusty Draper,deep adult standards,1953,109,65,70,-2,14,85,146,79,3,26,1950,0
3,Only Because,The Platters,adult standards,1957,73,28,55,-10,9,47,174,85,3,44,1950,0
4,Chicago - Remastered,Frank Sinatra,adult standards,1958,148,46,51,-10,40,79,134,61,7,47,1950,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,SeÃ±orita,Shawn Mendes,canadian pop,2019,117,55,76,-6,8,75,191,4,3,88,2010,0
656,bad guy,Billie Eilish,electropop,2019,135,43,70,-11,10,56,194,33,38,94,2010,0
657,Marianne,The Hilltoppers,deep adult standards,2019,106,55,71,-8,19,82,137,73,4,33,1950,1
658,Someone Elses Roses,Joan Regan,unknown,2019,100,14,29,-10,15,32,143,89,3,34,1950,1
659,When You Love Someone,James TW,neo mellow,2019,126,45,68,-6,5,35,217,26,3,76,2010,0

In [20]:
print(combined_df["incoherent_year"].sum(), "incoherent years")

189 incoherent years

We'll keep this column for now to have as an option later, although I'm not sure it'll make a difference.